// vue-interview-setup/src/components/Cart.vue
<script setup lang="ts">
  import Item from '../components/Item.vue';
  import { ref } from 'vue';

  const grandCount = ref<number>(0);
  const items = ref<{id: number}[]>([{id: 1}]);

  const handleIncreaseTotal = (amt: number) => grandCount.value += amt;

  const handleDecreaseTotal = (amt: number) => {
    const value = grandCount.value - amt;
    value < 0 ? grandCount.value = 0 : grandCount.value -= amt;
  }

  const handleAddItem = () => {
    const lastId = items.value[items.value.length - 1].id;
    items.value = [...items.value, {id: lastId + 1}]
  }

  const handleRemoveItem = (id: number, amt: number) => {
    handleDecreaseTotal(amt);
    items.value = [...items.value.filter(item => item.id !== id)];
    // console.log(`${JSON.stringify([...items.value.filter(item => item.id !== id)])}`)
  }

</script>

<template>
  <div>
    <div>Grand Total: {{ grandCount }}</div>
    <div class="list">
      <Item
        v-for="{id} in items" :key="id" 
        :id="id"
        @increase-count="handleIncreaseTotal"
        @decrease-count="handleDecreaseTotal"
        @add-clicked="handleAddItem"
        @remove-clicked="handleRemoveItem"
        :remove-btn-disabled="items.length < 2"
      />
    </div>
  </div>
</template>


<style scoped>
  .list {
    display: flex;
    flex-direction: column;
    gap: 5px;
  }
</style>

// interview-setup/components/Cart.tsx
import { useCallback, useState, type CSSProperties } from "react";
import Item from "./Item";

const Cart = () => {
  const [totalCount, setTotalCount] = useState<number>(0);
  const [items, setItems] = useState<{ id: number }[]>([{ id: 1 }]);

  const increaseTotalCount = useCallback(
    (amt: number) => {
      setTotalCount((prev) => prev + amt);
    },
    [setTotalCount]
  );

  const decreaseTotalCount = useCallback(
    (amt: number) => {
      setTotalCount((prev) => {
        const value = prev - amt;
        return value < 0 ? 0 : value;
      });
    },
    [setTotalCount]
  );

  const addToItems = useCallback(() => {
    setItems((prevItems) => {
      const lastId = prevItems[prevItems.length - 1].id;
      return [...prevItems, { id: lastId + 1 }];
    });
  }, [setItems]);

  const removeFromItems = useCallback(
    (id: number) => {
      // if (items.length <= 1) return;
      setItems((prevItems) => [...prevItems.filter((item) => item.id !== id)]);
    },
    [setItems]
  );

  return (
    <>
      <div>
        <div>Total Count: {totalCount}</div>
        <div style={styles.listContainer}>
          {items.map(({ id }) => (
            <Item
              key={id}
              id={id}
              clickPlus={increaseTotalCount}
              clickMinus={decreaseTotalCount}
              clickAdd={addToItems}
              clickRemove={removeFromItems}
              removeBtnDisabled={items.length <= 1}
            />
          ))}
        </div>
      </div>
    </>
  );
};

const styles: { [key: string]: CSSProperties } = {
  listContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
};

export default Cart;
