// vue-interview-setup/src/components/Item.vue
<script setup lang="ts">
import { ref } from "vue";

const { id, removeBtnDisabled } = defineProps<{
  id: number
  removeBtnDisabled: boolean
}>();

const emit = defineEmits<{
  increaseCount: [amt: number],
  decreaseCount: [amt: number],
  addClicked: []
  removeClicked: [id: number, amt: number]
}>()
const count = ref<number>(0);

const handleClickPlus = () => {
  count.value += 1;
  emit('increaseCount', 1)
}

const handleClickMinus = () => {
  const value = count.value - 1;
  value < 0 ? count.value = 0 : count.value -= 1;
  emit('decreaseCount', 1);
}

const handleClickRemove = () => {
  emit('removeClicked', id, count.value);
}

const handleClickAdd = () => {
 emit('addClicked')
}
</script>

<template>
  <div class="item">
    <button @click="handleClickMinus" :disabled="count <= 0">-</button>
    {{ count }}
    <button @click="handleClickPlus">+</button>
    <button class="add" @click="handleClickAdd">Add</button>
    <button class="remove" @click="handleClickRemove" :disabled="removeBtnDisabled">Remove</button>
  </div>
</template>

<style scoped>
  .item {
    display: flex;
    flex-direction: row;
    gap: 10px;
    align-items: center;
  }
  .remove {
    background-color: red;
  }
  .add {
    background-color: green
  }
  
</style>

// interview-setup/components/Item.tsx
import { useState, type CSSProperties } from "react";

type ItemProps = {
  clickAdd: () => void;
  clickRemove: (id: number) => void;
  clickPlus: (amt: number) => void;
  clickMinus: (amt: number) => void;
  id: number;
  removeBtnDisabled: boolean;
};

const Item = ({
  clickMinus,
  clickPlus,
  clickAdd,
  clickRemove,
  id,
  removeBtnDisabled,
}: ItemProps) => {
  const [count, setCount] = useState<number>(0);

  const handleClickPlus = () => {
    clickPlus(1);
    setCount((prev) => prev + 1);
  };

  const handleClickMinus = () => {
    setCount((prev) => {
      const value = prev - 1;
      return value <= 0 ? 0 : value;
    });
    clickMinus(1);
  };

  const handleClickAdd = () => {
    clickAdd();
  };

  const handleClickRemove = () => {
    clickMinus(count);
    clickRemove(id);
  };

  return (
    <>
      <div style={styles.container}>
        <button
          style={styles.plusAdd}
          onClick={handleClickMinus}
          disabled={count < 1}
        >
          -
        </button>
        {count}
        <button style={styles.plusAdd} onClick={handleClickPlus}>
          +
        </button>
        <button style={styles.add} onClick={handleClickAdd}>
          Add
        </button>
        <button
          style={styles.remove}
          onClick={handleClickRemove}
          disabled={removeBtnDisabled}
        >
          Remove
        </button>
      </div>
    </>
  );
};

const styles: { [key: string]: CSSProperties } = {
  container: {
    display: "flex",
    flexDirection: "row",
    gap: "5px",
    alignItems: "center",
    marginTop: "10px",
  },
  add: {
    backgroundColor: "green",
    color: "#fff",
  },
  remove: {
    backgroundColor: "red",
    color: "#fff",
  },
  title: {
    marginBottom: "20px",
  },
  plusAdd: {
    backgroundColor: "white",
    color: "black",
  },
};

export default Item;
